name: Daily Arden Scraper

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        run: pip install selenium webdriver-manager

      - name: Scripti Calistir
        run: python Codes/Markets/Arden/arden_scraper.py

      - name: Verileri Kaydet ve Pushla
        run: |
          git config --global user.name "Scraper Bot"
          git config --global user.email "bot@github.com"
          git add Datas/Markets/Arden/*.csv || echo "Dosya yok"
          git commit -m "Arden Veri Güncelleme: $(date +'%Y-%m-%d')" || echo "Degisiklik yok"
          git push
