name: Kale Market Daily Scrape

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} # Projedeki özel izni kullanır
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run scraper
        run: |
          python Codes/Markets/Kale/kale_scraper.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add Datas/Markets/Kale/*.csv
          git commit -m "Auto-update: Kale product data for $(date +'%Y-%m-%d')" || exit 0
          git pull --rebase origin master
          git push origin HEAD:master
