name: Kira_Botu_Otomasyon

on:
  schedule:
    - cron: '0 9 * * *' # Her gün Türkiye saatiyle öğlen 12:00'de çalışır
  workflow_dispatch: # Manuel çalıştırma butonu ekler

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: |
          pip install -r requirements.txt

      - name: Botu Calistir
        run: python sahibinden_kira_botu.py

      - name: Verileri Kaydet
        run: |
          git config --global user.name "Github-Bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Veri Guncelleme: $(date +'%Y-%m-%d')" || exit 0
          git push
